"""ajout champ notes au modèle CashMovement

Revision ID: 05d18bd637d0
Revises: f895bfcbdbd2
Create Date: 2025-06-29 04:46:01.613304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d18bd637d0'
down_revision = 'f895bfcbdbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_movement', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
