"""Ajout du champ payment_method au modèle Purchase

Revision ID: 187fe6b7617a
Revises: 637a8480f443
Create Date: 2025-10-19 01:43:24.826883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187fe6b7617a'
down_revision = '637a8480f443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
