"""Ajout module inventaire physique vs théorique

Revision ID: 1a3472678c27
Revises: 1ed5294c76ab
Create Date: 2025-10-20 01:40:02.095588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3472678c27'
down_revision = '1ed5294c76ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('include_ingredients_magasin', sa.Boolean(), nullable=True),
    sa.Column('include_ingredients_local', sa.Boolean(), nullable=True),
    sa.Column('include_consommables', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('EN_COURS', 'COMPLETE', 'VALIDE', 'CLOTURE', name='inventorystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('products_with_variance', sa.Integer(), nullable=True),
    sa.Column('total_variance_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventories_inventory_date'), ['inventory_date'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('theoretical_stock', sa.Float(), nullable=False),
    sa.Column('physical_stock', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('variance_percentage', sa.Float(), nullable=True),
    sa.Column('variance_level', sa.Enum('OK', 'NORMAL', 'CRITIQUE', name='variancelevel'), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('variance_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('adjustment_reason', sa.Enum('INVENDU_DONNE', 'PEREMPTION', 'VOL_PERTE', 'ERREUR_SAISIE', 'VENTE_NON_ENREGISTREE', 'PRODUCTION_NON_DECLAREE', 'AUTRE', name='adjustmentreason'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('counted_by_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_applied', sa.Boolean(), nullable=True),
    sa.Column('adjustment_applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_ingredients_magasin', sa.Float(), nullable=True),
    sa.Column('stock_ingredients_local', sa.Float(), nullable=True),
    sa.Column('stock_consommables', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_snapshots')
    op.drop_table('inventory_items')
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventories_inventory_date'))

    op.drop_table('inventories')
    # ### end Alembic commands ###
