"""Add can_be_purchased field to products for finished products that can be purchased

Revision ID: 23adf923c0a3
Revises: e07ed1692051
Create Date: 2025-11-25 23:05:55.311226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '23adf923c0a3'
down_revision = 'e07ed1692051'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Vérifie si une colonne existe dans une table"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('products', 'can_be_purchased'):
        with op.batch_alter_table('products', schema=None) as batch_op:
            batch_op.add_column(sa.Column('can_be_purchased', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('can_be_purchased')

    # ### end Alembic commands ###
