"""Add historical_accounting_data table for Prophet and AI analysis

Revision ID: 365191f90e87
Revises: 64200a1f79d0
Create Date: 2025-11-18 01:55:56.170844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '365191f90e87'
down_revision = '64200a1f79d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_accounting_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchases', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salaries', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_accounting_data', schema=None) as batch_op:
        batch_op.create_index('idx_historical_data_date', ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_accounting_data_record_date'), ['record_date'], unique=True)

    op.drop_table('business_config')
    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        # Ajouter la colonne year comme nullable d'abord
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Remplir les valeurs NULL avec l'année depuis start_date (hors du batch_alter_table)
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE accounting_fiscal_years 
        SET year = EXTRACT(YEAR FROM start_date)::INTEGER 
        WHERE year IS NULL
    """))
    
    # Maintenant rendre la colonne NOT NULL et continuer les modifications
    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        batch_op.alter_column('year', nullable=False)
        batch_op.create_unique_constraint(None, ['year'])
        batch_op.drop_constraint(batch_op.f('accounting_fiscal_years_closed_by_id_fkey'), type_='foreignkey')
        batch_op.drop_column('is_current')
        batch_op.drop_column('closed_by_id')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('name')

    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        # Ajouter entry_number comme nullable d'abord
        batch_op.add_column(sa.Column('entry_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fiscal_year_id', sa.Integer(), nullable=True))
    
    # Remplir entry_number pour les enregistrements existants
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE accounting_journal_entries 
        SET entry_number = 'ENTRY-' || id::TEXT 
        WHERE entry_number IS NULL
    """))
    
    # Maintenant rendre entry_number NOT NULL
    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.alter_column('entry_number', nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('accounting_journal_entries_reference_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_accounting_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_unique_constraint(None, ['entry_number'])
        batch_op.drop_constraint(batch_op.f('accounting_journal_entries_validated_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('accounting_journal_entries_cash_movement_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('accounting_journal_entries_purchase_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('accounting_journal_entries_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounting_fiscal_years', ['fiscal_year_id'], ['id'])
        batch_op.drop_column('validated_at')
        batch_op.drop_column('order_id')
        batch_op.drop_column('is_validated')
        batch_op.drop_column('cash_movement_id')
        batch_op.drop_column('validated_by_id')
        batch_op.drop_column('reference_document')
        batch_op.drop_column('sequence')
        batch_op.drop_column('purchase_id')
        batch_op.drop_column('accounting_date')

    with op.batch_alter_table('accounting_journal_entry_lines', schema=None) as batch_op:
        # Ajouter entry_id comme nullable d'abord
        batch_op.add_column(sa.Column('entry_id', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('line_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Copier journal_entry_id vers entry_id pour les enregistrements existants (hors du batch)
    conn.execute(sa.text("""
        UPDATE accounting_journal_entry_lines 
        SET entry_id = journal_entry_id 
        WHERE entry_id IS NULL AND journal_entry_id IS NOT NULL
    """))
    
    # Maintenant rendre entry_id NOT NULL et continuer
    with op.batch_alter_table('accounting_journal_entry_lines', schema=None) as batch_op:
        batch_op.alter_column('entry_id', nullable=False)
        batch_op.drop_constraint(batch_op.f('accounting_journal_entry_lines_journal_entry_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounting_journal_entries', ['entry_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('journal_entry_id')
        batch_op.drop_column('reference')

    with op.batch_alter_table('accounting_journals', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('accounting_journals_default_credit_account_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('accounting_journals_default_debit_account_id_fkey'), type_='foreignkey')
        batch_op.drop_column('default_credit_account_id')
        batch_op.drop_column('default_debit_account_id')
        batch_op.drop_column('sequence')
        batch_op.drop_column('description')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('accounting_journals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_debit_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_credit_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('accounting_journals_default_debit_account_id_fkey'), 'accounting_accounts', ['default_debit_account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('accounting_journals_default_credit_account_id_fkey'), 'accounting_accounts', ['default_credit_account_id'], ['id'])
        batch_op.alter_column('code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('accounting_journal_entry_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('accounting_journal_entry_lines_journal_entry_id_fkey'), 'accounting_journal_entries', ['journal_entry_id'], ['id'])
        batch_op.alter_column('line_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('entry_id')

    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounting_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reference_document', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('validated_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cash_movement_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_validated', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('validated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('accounting_journal_entries_order_id_fkey'), 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('accounting_journal_entries_purchase_id_fkey'), 'purchases', ['purchase_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('accounting_journal_entries_cash_movement_id_fkey'), 'cash_movement', ['cash_movement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('accounting_journal_entries_validated_by_id_fkey'), 'users', ['validated_by_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_accounting_journal_entries_entry_date'))
        batch_op.create_unique_constraint(batch_op.f('accounting_journal_entries_reference_key'), ['reference'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('fiscal_year_id')
        batch_op.drop_column('entry_number')

    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('closed_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('accounting_fiscal_years_closed_by_id_fkey'), 'users', ['closed_by_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('year')

    op.create_table('business_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monthly_objective', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('daily_objective', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('yearly_objective', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock_rotation_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('low_stock_threshold_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quality_target_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('customer_satisfaction_target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('standard_work_hours_per_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('overtime_rate_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('business_config_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_config_pkey'))
    )
    with op.batch_alter_table('historical_accounting_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_accounting_data_record_date'))
        batch_op.drop_index('idx_historical_data_date')

    op.drop_table('historical_accounting_data')
    # ### end Alembic commands ###
