"""Add can_be_sold field to products

Revision ID: 3ca221d643bd
Revises: 7950b875b780
Create Date: 2025-11-25 22:08:43.519679

Note: Cette migration référence 7950b875b780 (migration initiale VPS) 
car l'historique des migrations sur le VPS est différent du local.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca221d643bd'
down_revision = '7950b875b780'  # Migration initiale VPS (au lieu de 365191f90e87)
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_objective', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_objective', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('yearly_objective', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_rotation_days', sa.Integer(), nullable=False),
    sa.Column('quality_target_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('standard_work_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True))

    # Ajouter is_validated comme nullable d'abord
    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_validated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('validated_by_id', sa.Integer(), nullable=True))
    
    # Mettre à jour les valeurs existantes à False (en dehors du batch)
    op.execute("UPDATE accounting_journal_entries SET is_validated = false WHERE is_validated IS NULL")
    
    # Maintenant rendre la colonne NOT NULL
    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.alter_column('is_validated', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['validated_by_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_be_sold', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('can_be_sold')

    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('validated_by_id')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('is_validated')

    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    op.drop_table('business_config')
    # ### end Alembic commands ###
