"""Add can_be_sold field to products

Revision ID: 3ca221d643bd
Revises: add_waste_weekly_simple
Create Date: 2025-11-25 22:08:43.519679

Note: Cette migration référence add_waste_weekly_simple pour créer une chaîne 
cohérente avec l'historique VPS. Utilise des vérifications "IF NOT EXISTS" pour
compatibilité avec les bases déjà migrées manuellement.

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3ca221d643bd'
down_revision = 'add_waste_weekly_simple'  # Après add_waste_weekly_simple
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Vérifie si une table existe"""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Vérifie si une colonne existe dans une table"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Créer business_config seulement si elle n'existe pas
    if not table_exists('business_config'):
        op.create_table('business_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('monthly_objective', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('daily_objective', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('yearly_objective', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('stock_rotation_days', sa.Integer(), nullable=False),
        sa.Column('quality_target_percent', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('standard_work_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Ajouter is_current à accounting_fiscal_years si elle n'existe pas
    if not column_exists('accounting_fiscal_years', 'is_current'):
        with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=True))

    # Ajouter les colonnes de validation à accounting_journal_entries si elles n'existent pas
    if not column_exists('accounting_journal_entries', 'is_validated'):
        with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_validated', sa.Boolean(), nullable=True))
        op.execute("UPDATE accounting_journal_entries SET is_validated = false WHERE is_validated IS NULL")
        with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
            batch_op.alter_column('is_validated', nullable=False)
    
    if not column_exists('accounting_journal_entries', 'validated_at'):
        with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
            batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
    
    if not column_exists('accounting_journal_entries', 'validated_by_id'):
        with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
            batch_op.add_column(sa.Column('validated_by_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'users', ['validated_by_id'], ['id'])

    # Ajouter can_be_sold à products si elle n'existe pas
    if not column_exists('products', 'can_be_sold'):
        with op.batch_alter_table('products', schema=None) as batch_op:
            batch_op.add_column(sa.Column('can_be_sold', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('can_be_sold')

    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('validated_by_id')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('is_validated')

    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        batch_op.drop_column('is_current')

    op.drop_table('business_config')
    # ### end Alembic commands ###
