"""Change cost_price precision to 4 decimals

Revision ID: 50e8f489bfd2
Revises: d95e533afe39
Create Date: 2025-06-26 03:57:12.578065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e8f489bfd2'
down_revision = 'd95e533afe39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('cost_price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
