"""Ajout valeur_stock_ingredients_magasin et valeur_stock_ingredients_local à Product

Revision ID: 6a08ba707d0b
Revises: 50e8f489bfd2
Create Date: 2025-06-29 01:28:48.760889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a08ba707d0b'
down_revision = '50e8f489bfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valeur_stock_ingredients_magasin', sa.Numeric(precision=12, scale=4), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('valeur_stock_ingredients_local', sa.Numeric(precision=12, scale=4), server_default='0.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('valeur_stock_ingredients_local')
        batch_op.drop_column('valeur_stock_ingredients_magasin')

    # ### end Alembic commands ###
