"""ajout_module_paie_complet_work_hours_payroll_calculations

Revision ID: 9419cff9a6d1
Revises: b542da3a319d
Create Date: 2025-07-05 02:24:07.799359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9419cff9a6d1'
down_revision = 'b542da3a319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sick_days', sa.Integer(), nullable=False),
    sa.Column('vacation_days', sa.Integer(), nullable=False),
    sa.Column('other_absences', sa.Integer(), nullable=False),
    sa.Column('performance_bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transport_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meal_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_deduction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period_month', 'period_year', name='unique_employee_period')
    )
    op.create_table('payroll_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_hours_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('regular_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_bonuses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('social_security_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('unemployment_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('retirement_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('social_security_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unemployment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retirement_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_charges', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_hours_id'], ['work_hours.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period_month', 'period_year', name='unique_payroll_period')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_calculations')
    op.drop_table('work_hours')
    # ### end Alembic commands ###
