"""Ajout identifiants fiscaux B2B (RC, NIS, AI)

Revision ID: a93b61be4080
Revises: b2b_schema_updates
Create Date: 2025-12-23 00:58:03.128939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93b61be4080'
down_revision = 'b2b_schema_updates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rc_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nis_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_clients', schema=None) as batch_op:
        batch_op.drop_column('ai_number')
        batch_op.drop_column('nis_number')
        batch_op.drop_column('rc_number')

    # ### end Alembic commands ###
