"""Add sale_unit field to products for different sale unit than base unit

Revision ID: e07ed1692051
Revises: 3ca221d643bd
Create Date: 2025-11-25 22:35:17.105870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07ed1692051'
down_revision = '3ca221d643bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sale_unit')

    # ### end Alembic commands ###
