"""Ajout table attendance_records pour pointages ZKTeco

Revision ID: edeed46795b7
Revises: 9419cff9a6d1
Create Date: 2025-07-09 02:55:27.904251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edeed46795b7'
down_revision = '9419cff9a6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verification_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('processed', sa.Boolean(), nullable=True))
        batch_op.alter_column('punch_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_attendance_employee_date'))
        batch_op.drop_index(batch_op.f('idx_attendance_zk_user'))
        batch_op.create_index('idx_date_punch', ['timestamp', 'punch_type'], unique=False)
        batch_op.create_index('idx_employee_date', ['employee_id', 'timestamp'], unique=False)
        batch_op.drop_column('status')
        batch_op.drop_column('source')
        batch_op.drop_column('zk_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zk_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_employee_date')
        batch_op.drop_index('idx_date_punch')
        batch_op.create_index(batch_op.f('idx_attendance_zk_user'), ['zk_user_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendance_employee_date'), ['employee_id', 'timestamp'], unique=False)
        batch_op.alter_column('punch_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('processed')
        batch_op.drop_column('verification_type')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
