#!/bin/bash
echo "=== VÉRIFICATION SERVICE SYSTEMD ==="
echo ""
echo "Services contenant 'erp' ou 'gunicorn':"
sudo systemctl list-units --all | grep -i "erp\|gunicorn"
echo ""
echo "=== CONFIGURATION DU SERVICE ==="
sudo systemctl cat erp 2>/dev/null || sudo systemctl cat gunicorn 2>/dev/null || echo "Service non trouvé"
echo ""
echo "=== LOGS NGINX (erreurs) ==="
sudo tail -50 /var/log/nginx/erp_error.log 2>/dev/null | grep -i "2025-12-09.*\(12:\|13:\|21:\|22:\)" || echo "Aucune erreur trouvée"
echo ""
echo "=== LOGS NGINX (accès) ==="
sudo tail -100 /var/log/nginx/erp_access.log 2>/dev/null | grep -i "complete-sale\|/sales/api" | tail -20 || echo "Aucun accès trouvé"
